OPEN_AI_API_KEY: 12345
TAVILY_API_KEY: 12345
LANGCHAIN_API_KEY: 12345
LANGCHAIN_TRACING_V2: true
LANGCHAIN_ENDPOINT: https://api.smith.langchain.com
LANGCHAIN_HUB_API_URL: https://api.hub.langchain.com
LANGCHAIN_WANDB_TRACING: true
WANDB_PROJECT: 12345